// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using gerenciamento_Ti.Database;

#nullable disable

namespace gerenciamento_Ti.Migrations
{
    [DbContext(typeof(GerenciamentoDbContext))]
    [Migration("20260721141608_EstruturaBasicaChamados")]
    partial class EstruturaBasicaChamados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("gerenciamento_Ti.Entities.Chamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Fim")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Solucao")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Chamado");
                });

            modelBuilder.Entity("gerenciamento_Ti.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome_Loja")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("gerenciamento_Ti.Entities.Equipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("integer");

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Numero_Serie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TipoEquipamentoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("TipoEquipamentoId");

                    b.ToTable("Equipamento");
                });

            modelBuilder.Entity("gerenciamento_Ti.Entities.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Contato")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Esta_Ativo_Plataforma")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Usuario_Ativo")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Funcionario");
                });

            modelBuilder.Entity("gerenciamento_Ti.Entities.MensagemChamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChamadoId")
                        .HasColumnType("integer");

                    b.Property<bool>("ConfirmaRecebido")
                        .HasColumnType("boolean");

                    b.Property<bool>("Enviado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Envio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioChamadoId")
                        .HasColumnType("integer");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId");

                    b.HasIndex("UsuarioChamadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("MensagemChamado");
                });

            modelBuilder.Entity("gerenciamento_Ti.Entities.TipoEquipamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Observacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TipoEquipamento");
                });

            modelBuilder.Entity("gerenciamento_Ti.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("gerenciamento_Ti.Entities.UsuarioChamado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChamadoId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("UsuarioChamado");
                });

            modelBuilder.Entity("gerenciamento_Ti.Entities.Empresa", b =>
                {
                    b.HasOne("gerenciamento_Ti.Entities.Funcionario", "Funcionario")
                        .WithMany("Empresas")
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("gerenciamento_Ti.Entities.Equipamento", b =>
                {
                    b.HasOne("gerenciamento_Ti.Entities.Empresa", "Empresa")
                        .WithMany("Equipamentos")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gerenciamento_Ti.Entities.Funcionario", "Funcionario")
                        .WithMany("Equipamentos")
                        .HasForeignKey("FuncionarioId");

                    b.HasOne("gerenciamento_Ti.Entities.TipoEquipamento", "TipoEquipamento")
                        .WithMany("Equipamento")
                        .HasForeignKey("TipoEquipamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Funcionario");

                    b.Navigation("TipoEquipamento");
                });

            modelBuilder.Entity("gerenciamento_Ti.Entities.MensagemChamado", b =>
                {
                    b.HasOne("gerenciamento_Ti.Entities.Chamado", "Chamado")
                        .WithMany("MensagemChamado")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gerenciamento_Ti.Entities.UsuarioChamado", "UsuarioChamado")
                        .WithMany()
                        .HasForeignKey("UsuarioChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gerenciamento_Ti.Entities.Usuario", null)
                        .WithMany("MensagemChamado")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Chamado");

                    b.Navigation("UsuarioChamado");
                });

            modelBuilder.Entity("gerenciamento_Ti.Entities.UsuarioChamado", b =>
                {
                    b.HasOne("gerenciamento_Ti.Entities.Chamado", "Chamado")
                        .WithMany("UsuarioChamado")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("gerenciamento_Ti.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioChamado")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chamado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("gerenciamento_Ti.Entities.Chamado", b =>
                {
                    b.Navigation("MensagemChamado");

                    b.Navigation("UsuarioChamado");
                });

            modelBuilder.Entity("gerenciamento_Ti.Entities.Empresa", b =>
                {
                    b.Navigation("Equipamentos");
                });

            modelBuilder.Entity("gerenciamento_Ti.Entities.Funcionario", b =>
                {
                    b.Navigation("Empresas");

                    b.Navigation("Equipamentos");
                });

            modelBuilder.Entity("gerenciamento_Ti.Entities.TipoEquipamento", b =>
                {
                    b.Navigation("Equipamento");
                });

            modelBuilder.Entity("gerenciamento_Ti.Entities.Usuario", b =>
                {
                    b.Navigation("MensagemChamado");

                    b.Navigation("UsuarioChamado");
                });
#pragma warning restore 612, 618
        }
    }
}
